#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libatasmart
Version  : 0.19
Release  : 5
URL      : http://0pointer.de/public/libatasmart-0.19.tar.xz
Source0  : http://0pointer.de/public/libatasmart-0.19.tar.xz
Summary  : ATA S.M.A.R.T. Reading and Parsing Library
Group    : Development/Tools
License  : LGPL-2.1
Requires: libatasmart-bin = %{version}-%{release}
Requires: libatasmart-data = %{version}-%{release}
Requires: libatasmart-lib = %{version}-%{release}
BuildRequires : pkgconfig(libudev)

%description
LIBATASMART ATA S.M.A.R.T. Reading and Parsing Library
GIT:
git://git.0pointer.de/libatasmart.git

%package bin
Summary: bin components for the libatasmart package.
Group: Binaries
Requires: libatasmart-data = %{version}-%{release}

%description bin
bin components for the libatasmart package.


%package data
Summary: data components for the libatasmart package.
Group: Data

%description data
data components for the libatasmart package.


%package dev
Summary: dev components for the libatasmart package.
Group: Development
Requires: libatasmart-lib = %{version}-%{release}
Requires: libatasmart-bin = %{version}-%{release}
Requires: libatasmart-data = %{version}-%{release}
Provides: libatasmart-devel = %{version}-%{release}
Requires: libatasmart = %{version}-%{release}

%description dev
dev components for the libatasmart package.


%package doc
Summary: doc components for the libatasmart package.
Group: Documentation

%description doc
doc components for the libatasmart package.


%package lib
Summary: lib components for the libatasmart package.
Group: Libraries
Requires: libatasmart-data = %{version}-%{release}

%description lib
lib components for the libatasmart package.


%prep
%setup -q -n libatasmart-0.19
cd %{_builddir}/libatasmart-0.19

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604352829
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1604352829
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/skdump
/usr/bin/sktest

%files data
%defattr(-,root,root,-)
/usr/share/vala/vapi/atasmart.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/atasmart.h
/usr/lib64/libatasmart.so
/usr/lib64/pkgconfig/libatasmart.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libatasmart/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libatasmart.so.4
/usr/lib64/libatasmart.so.4.0.5
