#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libatasmart
Version  : 0.19
Release  : 1
URL      : http://0pointer.de/public/libatasmart-0.19.tar.xz
Source0  : http://0pointer.de/public/libatasmart-0.19.tar.xz
Summary  : ATA S.M.A.R.T. Reading and Parsing Library
Group    : Development/Tools
License  : LGPL-2.1
Requires: libatasmart-bin
Requires: libatasmart-lib
Requires: libatasmart-doc
Requires: libatasmart-data
BuildRequires : pkgconfig(libudev)

%description
LIBATASMART ATA S.M.A.R.T. Reading and Parsing Library
GIT:
git://git.0pointer.de/libatasmart.git

%package bin
Summary: bin components for the libatasmart package.
Group: Binaries
Requires: libatasmart-data

%description bin
bin components for the libatasmart package.


%package data
Summary: data components for the libatasmart package.
Group: Data

%description data
data components for the libatasmart package.


%package dev
Summary: dev components for the libatasmart package.
Group: Development
Requires: libatasmart-lib
Requires: libatasmart-bin
Requires: libatasmart-data
Provides: libatasmart-devel

%description dev
dev components for the libatasmart package.


%package doc
Summary: doc components for the libatasmart package.
Group: Documentation

%description doc
doc components for the libatasmart package.


%package lib
Summary: lib components for the libatasmart package.
Group: Libraries
Requires: libatasmart-data

%description lib
lib components for the libatasmart package.


%prep
%setup -q -n libatasmart-0.19

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1513198908
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1513198908
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/skdump
/usr/bin/sktest

%files data
%defattr(-,root,root,-)
/usr/share/vala/vapi/atasmart.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libatasmart.so
/usr/lib64/pkgconfig/libatasmart.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/libatasmart/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libatasmart.so.4
/usr/lib64/libatasmart.so.4.0.5
